name: Python Linter (Pylint)

on:
  push:
    branches:
      - main  # Run when pushing to the main branch
      - '**/feature/*'  # Run on feature branches

jobs:
  lint:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code in your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use (e.g., 3.9)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install pylint  # Install pylint linter

      - name: Run pylint
        run: |
          pylint **/*.py  # Run pylint on all Python files in the repository
